
- name: Create the base application directory
  file:
    path: "/opt/app"
    state: directory
    mode: "0755"

- name: Copy docker-compose.yml
  copy:
    src: "../docker-compose/docker-compose.yml"
    dest: "/opt/app/docker-compose.yml"
    mode: "0644"

- name: Copy traefik.yml
  copy:
    src: "../docker-compose/traefik.yml"
    dest: "/opt/app/traefik.yml"
    mode: "0644"

- name: Copy environment file
  copy:
    src: "../docker-compose/.env"
    dest: "/opt/app/.env"
    mode: "0644"

- name: Create the monitoring directory
  file:
    path: "/opt/app/monitoring"
    state: directory
    mode: "0755"

- name: Create the monitoring data directory
  file:
    path: "/opt/app/monitoring/data"
    state: directory
    mode: "0777"

- name: Copy monitoring docker-compose.yml
  copy:
    src: "../docker-compose/monitoring/docker-compose.yml"
    dest: "/opt/app/monitoring/docker-compose.yml"
    mode: "0644"

- name: Copy prometheus.yml
  copy:
    src: "../docker-compose/monitoring/prometheus.yml"
    dest: "/opt/app/monitoring/prometheus.yml"
    mode: "0644"

- name: Copy loki-config.yaml
  copy:
    src: "../docker-compose/monitoring/loki-config.yaml"
    dest: "/opt/app/monitoring/loki-config.yaml"
    mode: "0644"

- name: Copy promtail-config.yml
  copy:
    src: "../docker-compose/monitoring/promtail-config.yaml"
    dest: "/opt/app/monitoring/promtail-config.yaml"
    mode: "0644"

- name: Copy dashboard-providers.yml
  copy:
    src: "../docker-compose/monitoring/dashboard-providers.yml"
    dest: "/opt/app/monitoring/dashboard-providers.yml"
    mode: "0644"

- name: Copy datasources.yml
  copy:
    src: "../docker-compose/monitoring/datasources.yml"
    dest: "/opt/app/monitoring/datasources.yml"
    mode: "0644"

- name: Copy .env
  copy:
    src: "../docker-compose/monitoring/.env"
    dest: "/opt/app/monitoring/.env"
    mode: "0644"

- name: Set permissions for /opt/app/monitoring/data
  file:
    path: "/opt/app/monitoring/data"
    state: directory
    mode: "0777"