
name: Deploy Monitoring Stack

on:
  workflow_run:
    workflows:
      - Terraform Apply
    types:
      - completed
    branches:
      - infra_main
      - infra_features

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Debugging workflow status
        run: |
          echo "Workflow status: ${{ github.event.workflow_run.conclusion }}"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List Available Artifacts
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/artifacts | jq '.artifacts[] | .name'
      

      - name: Download Terraform Output Artifact
        uses: actions/download-artifact@v3
        with:
          name: inventory-file
          path: ./terraform

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
        
      - name: Set up SSH private key for Ansible
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa          

      - name: Run Ansible Playbook
        run: ansible-playbook -i ./terraform/inventory.ini ./ansible/playbook-monitoring.yml
