name: Placeholders for GitHub Actions Workflows

on:
  push:
    branches:
      - deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Placeholder job
        run: echo "Success"
