name: Build, Push, and Update Docker Images

on:
  push:
    branches:
      - integration

permissions:
  contents: write

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: integration

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract short SHA for tagging
        id: vars
        run: |
          echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build, tag, and push Frontend Docker image
        run: |
          docker build -t utibeokon/frontend:latest ./app/frontend
          docker tag utibeokon/frontend:latest utibeokon/frontend:${{ env.SHA_SHORT }}
          docker push utibeokon/frontend:latest
          docker push utibeokon/frontend:${{ env.SHA_SHORT }}

      - name: Build, tag, and push Backend Docker image
        run: |
          docker build -t utibeokon/backend:latest ./app/backend
          docker tag utibeokon/backend:latest utibeokon/backend:${{ env.SHA_SHORT }}
          docker push utibeokon/backend:latest
          docker push utibeokon/backend:${{ env.SHA_SHORT }}

    outputs:
      sha_short: ${{ env.SHA_SHORT }}

  update-compose-file:
    needs: build-and-push-images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: integration

      - name: Update docker-compose.yml with new image tags
        run: |
          sed -i "s|image: utibeokon/frontend:.*$|image: utibeokon/frontend:${{ needs.build-and-push-images.outputs.sha_short }}|" docker-compose/docker-compose.yml
          sed -i "s|image: utibeokon/backend:.*$|image: utibeokon/backend:${{ needs.build-and-push-images.outputs.sha_short }}|" docker-compose/docker-compose.yml

      - name: Commit and push updated docker-compose.yml
        run: |
          git config --global user.name "yutee"
          git config --global user.email "yuteenightxi@gmail.com"
          git add docker-compose/docker-compose.yml
          git commit -m "Update docker-compose.yml with image tags ${{ needs.build-and-push-images.outputs.sha_short }}"
          git push origin integration