
name: Terraform Apply

on:
  push:
    branches:
      - infra_main

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Apply Terraform configuration
        working-directory: ./terraform
        env:
          TF_VAR_ssh_key_path: ${{ secrets.SSH_PUBLIC_KEY }}
        run: |
            terraform apply -auto-approve \
            -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
            -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
            -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}"

      - name: Save Ansible Inventory
        working-directory: ./terraform
        run: |
            terraform output -raw ansible_inventory > inventory.ini
    
      - name: Upload Inventory to Azure Blob
        uses: azure/CLI@v1
        with:
          inlineScript: |
                az storage blob upload \
                  --container-name pipeline-files \
                  --file ./terraform/inventory.ini \
                  --name inventory.ini \
                  --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
                  --account-key ${{ secrets.AZURE_STORAGE_KEY }}          
